### ISSUE TITLE
Using WebDAV error: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by RobTranquillo** [bxb100/action-upload#67]
Hello and thank you for the action.

when using webdav I alway get an error and dont know how to handle.

```
Run bxb100/action-upload@main
Error: Upload files failed: TypeError: Cannot read properties of undefined (reading 'trim')
Error: Upload files failed
```

the action is super simple for test purposes:

```
name: WebDAV Test

on:
    workflow_dispatch:

jobs:
    ftp-upload:
        name: 🏗️ Upload to internal webserver
        runs-on: ubuntu-latest
        steps:

            # Create test content
            - name: Create test content on server
              run: |                    
                mkdir build
                echo "Hello World" > build/test1.txt

            # upload the project to internal webserver via WebDav
            - name: Upload to WebDAV
              uses: bxb100/action-upload@main
              with:
                provider: webdav
                provider_options: |
                    endpoint: ${{ secrets.WEBDAV_ENDPOINT }}
                    username: ${{ secrets.WEBDAV_USERNAME }}
                    password: ${{ secrets.WEBDAV_PASSWORD }}
                    root: /web/
                include: './**'
```

Any Ideas?

Best
Rob

**Comment by bxb100** [comment]
Hi Bob,

Sry, It is because the README.md had the wrong code instruction, `provider_options` need `key=value` not `key: value`

```diff

      # upload the project to internal webserver via WebDav
      - name: Upload to WebDAV
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
-            endpoint: ${{ secrets.WEBDAV_ENDPOINT }}
-            username: ${{ secrets.WEBDAV_USERNAME }}
-            password: ${{ secrets.WEBDAV_PASSWORD }}
-            root: /web/
+            endpoint= ${{ secrets.WEBDAV_ENDPOINT }}
+            username= ${{ secrets.WEBDAV_USERNAME }}
+            password= ${{ secrets.WEBDAV_PASSWORD }}
+            root= /web/
          include: './**'

```

I will fix it ASAP, Thanks

**Comment by RobTranquillo** [comment]
Thanks for fast update...  but did'nt fixed it for me.

I got 
```
Upload files failed: TypeError: Cannot read properties of undefined (reading 'trim')
```

with my action.

```
name: WebDAV Test

on:
    workflow_dispatch:

jobs:
    ftp-upload:
        name: 🏗️ Upload to internal webserver
        runs-on: ubuntu-latest
        steps:
            # Create test content
            - name: Create test content on server
              run: |                    
                pwd
                mkdir build
                echo "Hello World" > build/test1.txt

            # upload the project to internal webserver via WebDav
            - name: Upload to WebDAV
              uses: bxb100/action-upload@main
              with:
                provider: webdav
                provider_options: |
                    endpoint=${{ secrets.WEBDAV_ENDPOINT }}
                    username=${{ secrets.WEBDAV_USERNAME }}
                    password=${{ secrets.WEBDAV_PASSWORD }}
                    root: /web/
                include: './**'
```
 
Maybe because of the include clause? Can't find an explanation for it, so I tried something arbitrary.

Thank you and best regards
Rob
